(function(){function index(it
/*``*/) {
var out='<html><head><meta charset="UTF-8" /><title>Arschsuppe</title><link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet"><script>(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');ga(\'create\', \'UA-66910486-5\', \'auto\');ga(\'send\', \'pageview\');</script><meta name="viewport" content="width=device-width, initial-scale=1"><style>html, body {font-family: \'Lato\', sans-serif;}.meal {box-sizing: border-box;padding:20px;width:33.33%;font-size: 20px;display: flex;flex-wrap: wrap;//box-shadow: 5px 5px 25px 0 #040404;}h1 {text-align: center;padding-top: 30px;font-size: 44px;color: white;text-shadow: 0px 1px 40px black;}.meal > div {flex: 1;display: flex;flex-direction: column;box-shadow: 5px 5px 25px 0 #3c3c3c;}.category {background: #141E30;  background: -webkit-linear-gradient(to right, #243B55, #141E30);  background: linear-gradient(to right, #243B55, #141E30); width: 100%;min-height: 40px;color: white;text-transform: uppercase;display: flex;align-items: center;}.category h2 {padding-left: 10px;font-size: 20px;}.inner {padding: 0 10px;border:1px solid #fff;border-radius: 2px;background-color: white;flex: 1;padding-bottom: 50px;position: relative;}.name {padding-top: 10px;}.price {text-align: right;color: #6b6b6b;font-size: 24px;position: absolute;right: 10px;bottom: 10px;}@media screen and (max-width: 900px) {.meal {width:50%;}}@media screen and (max-width: 600px) {.meal {width:100%;}}.container {display:flex;flex-wrap:wrap;max-width: 1280px;margin: 30px auto 60px auto;}body {background-image: url(\'https://images.unsplash.com/photo-1495195134817-aeb325a55b65?w=1955&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D\');background-size: cover;background-attachment: fixed;background-position: right;}html {height:100%;}</style></head><body><h1>Essen an der Uni Bremen</h1><div class="container">'; for (const meal of it) { out+='<div class="meal" title="'+(meal.notes.join(", "))+'"> <div><div class="category"><h2>'+(meal.category)+'</h2></div><div class="inner"><div class="name">'+(meal.name.replace(/( \*)+ \*/g, ", "))+'</div><div class="price">'+(meal.prices.students.toFixed(2).replace(".", ","))+'&nbsp;€</div></div>     </div></div>'; } out+='</div></body></html>';return out;
}var itself=index, _encodeHTML=(function (doNotSkipEncoded) {
		var encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());if(typeof module!=='undefined' && module.exports) module.exports=itself;else if(typeof define==='function')define(function(){return itself;});else {window.render=window.render||{};window.render['index']=itself;}}());